version: "3.9"

services:
  dev:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    network_mode: host
    volumes:
      - ../:/workspace
    tty: true

  orin:
    build:
      context: ..
      dockerfile: docker/orin.Dockerfile
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - ../:/workspace
      - /usr/local/zed:/usr/local/zed
    tty: true
